version: '3.7'

volumes:
  database:
    driver: local

networks:
  wp-file-manager-solid-network:
    name: ${DOCKER_NETWORK}
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

services:
  database:
    container_name: wp-file-manager-solid_db
    image: mariadb:10.4
    command:
      --max_allowed_packet=1073741824
      --innodb_log_file_size=1073741824
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
      - ./docker/install:/var/www/install
    ports:
      - ${DOCKER_GATEWAY_IP}:3306:3306
    networks:
      - ${DOCKER_NETWORK}
  php:
    container_name: wp-file-manager-solid_php
    image: wpstaging/php:latest
    env_file: .env
    user: "1000:1000"
    depends_on:
      - database
    volumes:
      - ./docker/php/xdebug.ini:/etc/php/7.4/fpm/conf.d/xdebug.ini
      - ./docker/php/xdebug.ini:/etc/php/7.4/cli/conf.d/xdebug.ini
      - ./src:/var/www/wp-file-manager-solid.local/wp-content/plugins/wp-file-manager-solid
      - ./var/www:/var/www
      - ./docker/install:/var/www/install
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ${DOCKER_NETWORK}
  nginx:
    container_name: wp-file-manager-solid_nginx
    image: triplebits/nginx:latest
    depends_on:
      - database
      - php
    links:
      - php
    volumes:
      - ./var/www:/var/www
      - ./src:/var/www/wp-file-manager-solid.local/wp-content/plugins/wp-file-manager-solid
      - ./docker/nginx/sites-enabled/.:/etc/nginx/sites-enabled
    ports:
      - ${DOCKER_GATEWAY_IP}:80:80
      - ${DOCKER_GATEWAY_IP}:443:443
    networks:
      - ${DOCKER_NETWORK}